// Code generated by goctl. DO NOT EDIT.
package types

type ProductListRequest struct {
	BaseRequest
}

type ProductListReply struct {
	List  []*ProductListBasic `json:"list"`
	Count int64               `json:"count"`
}

type ProductListBasic struct {
	Identity  string `json:"identity"`
	Name      string `json:"name"`
	Key       string `json:"key"`
	CreatedAt string `json:"created_at"`
}

type BaseRequest struct {
	Page int    `json:"page,optional"`
	Size int    `json:",optional"`
	Name string `json:"name,optional"`
}

type DeviceListRequest struct {
	BaseRequest
}

type DeviceListBasic struct {
	Identity    string `json:"identity"`
	Name        string `json:"name"`
	Key         string `json:"key"`
	Secret      string `json:"secret"`
	ProductName string `json:"product_name"`
}

type DeviceListReply struct {
	List  []*DeviceListBasic `json:"list"`
	Count int64              `json:"count"`
}
